name: Backend Continuous Integration

on:
  # Automatic trigger on pull request events targeting the main branch and frontend application changes
  pull_request:
    branches:
      - main
    path:
      - 'backend/**'

  # On demand run
  workflow_dispatch:


# Jobs defined in the workflow
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: cd backend && pip install pipenv && pipenv install

      - name: Run linter
        run: cd backend && pip install flake8 && pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: cd backend && pip install pipenv && pipenv install

      - name: Run tests
        run: cd backend && pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: cd backend && pip install pipenv && pipenv install